analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      user: "{{ env_var('DBT_USER', 'postgres') }}"
      password: "{{ env_var('DBT_PASSWORD', 'postgres') }}"
      database: "{{ env_var('DBT_DATABASE', 'analytics_db') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public,analytics
    
    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: analytics
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10
      search_path: public,analytics
