version: 2

models:
  - name: pipeline_kpis
    description: "Pipeline KPIs with data quality checks"
    columns:
      - name: facility_id
        description: "Foreign key to facilities"
        tests:
          - not_null
          - relationships:
              to: source('raw', 'facilities')
              field: id
      - name: month
        description: "Month for the KPI aggregation"
        tests:
          - not_null
      - name: total_applications
        description: "Total number of applications"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: hired_count
        description: "Number of hired candidates"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: avg_time_to_fill_days
        description: "Average time to fill in days"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 365
              inclusive: true
              config:
                severity: warn
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - facility_id
            - month

  - name: compliance_kpis
    description: "Compliance KPIs with data quality checks"
    columns:
      - name: facility_id
        description: "Foreign key to facilities"
        tests:
          - not_null
          - relationships:
              to: source('raw', 'facilities')
              field: id
      - name: month
        description: "Month for the KPI aggregation"
        tests:
          - not_null
      - name: compliant_applications
        description: "Number of compliant applications"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: compliance_rate
        description: "Compliance rate (0-1)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true
      - name: violation_count
        description: "Number of violations"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - facility_id
            - month

  - name: revenue_kpis
    description: "Revenue KPIs with data quality checks"
    columns:
      - name: facility_id
        description: "Foreign key to facilities"
        tests:
          - not_null
          - relationships:
              to: source('raw', 'facilities')
              field: id
      - name: month
        description: "Month for the KPI aggregation"
        tests:
          - not_null
      - name: total_invoices
        description: "Total number of invoices"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: total_revenue
        description: "Total revenue"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: avg_revenue_per_invoice
        description: "Average revenue per invoice"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - facility_id
            - month

  - name: outreach_kpis
    description: "Outreach KPIs with data quality checks"
    columns:
      - name: facility_id
        description: "Foreign key to facilities"
        tests:
          - not_null
          - relationships:
              to: source('raw', 'facilities')
              field: id
      - name: month
        description: "Month for the KPI aggregation"
        tests:
          - not_null
      - name: channel
        description: "Outreach channel"
        tests:
          - not_null
          - accepted_values:
              values: ['email', 'phone', 'social', 'sms', 'other']
      - name: total_outreach
        description: "Total outreach count"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: response_rate
        description: "Response rate (0-1)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true
              config:
                severity: warn
      - name: conversion_rate
        description: "Conversion rate (0-1)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true
              config:
                severity: warn
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - facility_id
            - month
            - channel

  - name: combined_kpis
    description: "Combined KPIs with data quality checks"
    columns:
      - name: facility_id
        description: "Foreign key to facilities"
        tests:
          - not_null
          - relationships:
              to: source('raw', 'facilities')
              field: id
      - name: month
        description: "Month for the KPI aggregation"
        tests:
          - not_null
      - name: total_applications
        description: "Total number of applications"
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue"
        tests:
          - not_null
      - name: compliance_rate
        description: "Compliance rate (0-1)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1
              inclusive: true
              config:
                severity: warn
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - facility_id
            - month
